### ISSUE TITLE
V1.8 SKR 1.4 Wiring Diagram Outdated

### ISSUE THREAD

**Issue by dubjay2k** [bdbell/VoronDocs#12]
The wiring diagram for the V1.8 on this page is outdated: https://github.com/bdbell/VoronDocs/blob/master/official/build/electrical/v1_skr14_wiring.md

An updated version can be found here:
https://github.com/VoronDesign/Voron-1/blob/Voron1.8/Firmware/klipper_configurations/SKR_1.4/Voron_1_SKR_14_Wiring.pdf

There was a change in late September that changed the SSR wiring from the Servo header to the Neopixel header.

`Plug SSR Control for Heated Bed in to Servos (P2.0)` should now be `Plug SSR Control for Heated Bed in to Neopixel (P1.24)`

**Comment by dubjay2k** [comment]
Created PR to address.  https://github.com/bdbell/VoronDocs/pull/13

**Comment by bdbell** [comment]
PR merged.
