### ISSUE TITLE
Link to Calculating Driver Current Settings - Broken

### ISSUE THREAD

**Issue by barecool** [bdbell/VoronDocs#34]
On https://bdbell.github.io/VoronDocs/build/software/configuration.html#editing-printercfg 

the Calculating Driver Current Settings points to: https://bdbell.github.io/community/howto/120decibell/calculating_driver_current.md

instead of https://bdbell.github.io/VoronDocs/community/howto/120decibell/calculating_driver_current.html

however it returns 404

**Comment by bdbell** [comment]
Thanks.  I'll make sure this is updated on the production version.
