### ISSUE TITLE
V0 SSR wiring differences

### ISSUE THREAD

**Issue by bdbell** [bdbell/VoronDocs#7]
Nemgrea V2.199 V0.000Today at 8:43 PM
@120decibell V2.534 I believe the ssr speced for the v0 wires up differently than the cheap one that some people buy, documentation on how that cheaper ssr is wired would be helpful, unfortunately I don't know what that difference is atm but I believe it can be found on the magic studio aliexpress page that sells it as part of their kit

**Comment by dubjay2k** [comment]
Here is a diagram from the Magic Studios documentation for their SSR.

https://cdn.discordapp.com/attachments/696930677161197640/740567536311074816/unknown.png

**Comment by dubjay2k** [comment]
Trying to address this in https://github.com/bdbell/VoronDocs/pull/18.

**Comment by bdbell** [comment]
Closing as resolved by the PR.
